spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: wanghaibo
    password: whb.123
    virtual-host: /lzsz
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/lzsz_wemall?characterEncoding=utf-8&useSSL=false
    druid:
      max-active: 20
      min-idle: 3
      max-wait: 10000
      validation-query: SELECT 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
#      监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
server:
  port: 8000
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#自定义测试
my:
  test:
    name: wanghaibo
    type: aaaa
